=== johnnybubonic/OpTools/sys/BootSync/bootsync.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://git.square-r00t.net/OpTools/tree/sys/BootSync/"
           xmlns="http://git.square-r00t.net/OpTools/tree/sys/BootSync/"
           xmlns:bootsync="http://git.square-r00t.net/OpTools/tree/sys/BootSync/"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:simpleType name="diskdev">
        <xs:restriction base="xs:string">
            <xs:pattern value="/dev/([A-Za-z0-9+_-]+/)?[A-Za-z0-9+_-]+[0-9]?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="path">
        <xs:restriction base="xs:string">
            <xs:pattern value="/([A-Za-z0-9+_.-]+/)*[A-Za-z0-9+_.-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="relpath">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z0-9+_.-]+/)*[A-Za-z0-9+_.-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="bootsync">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="partitions" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="part" minOccurs="2" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="path" type="diskdev" use="required"/>
                                    <xs:attribute name="mount" type="path" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="partition_unique_mount">
                        <xs:selector xpath="bootsync:part"/>
                        <xs:field xpath="@mount"/>
                    </xs:unique>
                    <xs:unique name="partition_unique_path">
                        <xs:selector xpath="bootsync:part"/>
                        <xs:field xpath="@path"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="fileChecks" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="file" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="relpath">
                                            <xs:attribute name="isKernel" type="xs:boolean"
                                                          use="optional" default="false"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="filechk_unique">
                        <xs:selector xpath="bootsync:file"/>
                        <xs:field xpath="."/>
                    </xs:unique>
                </xs:element>
                <xs:element name="syncPaths" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="path" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="source" type="path" use="required"/>
                                    <xs:attribute name="target" type="relpath" use="required"/>
                                    <!-- TODO: make this optional? -->
                                    <xs:attribute name="pattern" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="syncpath_unique_source">
                        <xs:selector xpath="bootsync:path"/>
                        <xs:field xpath="@source"/>
                    </xs:unique>
                    <xs:unique name="syncpath_unique_target">
                        <xs:selector xpath="bootsync:path"/>
                        <xs:field xpath="@target"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== johnnybubonic/OpTools/sys/BootSync/sample.config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This example assumes Grub2 and UEFI. It should be flexible enough to tweak for other use cases
     if you know what the hell you're doing. -->
<!--
SEE prep.txt FOR WHAT MUST BE DONE BEFORE RUNNING BOOTSYNC.
-->
<bootsync xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://git.square-r00t.net/OpTools/tree/sys/BootSync/"
          xsi:schemaLocation="http://git.square-r00t.net/OpTools/plain/sys/BootSync/bootsync.xsd">
    <!-- The actual EFI System Partitions (ESP). At least two are required. -->
    <!-- Each drive should be prepared ahead of time with efibootmgr and grub-install (see prep.txt). -->
    <partitions>
        <!-- These should all be unique values.
             Don't do something dumb like mount the same partition on the same mountpoint. -->
        <!-- Future versions of this script may support things like UUIDs or labels as an alternative to path=,
             but in the meanwhile it relies on device paths explicitly. -->
        <part path="/dev/sdb1" mount="/mnt/boot1"/>
        <part path="/dev/sdd1" mount="/mnt/boot2"/>
    </partitions>
    <!-- If specified, the files in this container are checksummed to determine if a sync is required.
         If fileChecks isn't provided, we will always sync no matter what.
         These files will be evaluated to and synced to the ESP partitions with the same relative path.
         i.e. (part[@mount])/(file)

         "isKernel" is by default false, but if true it is treated specially to get a kernel version.
         This is to notify you if a reboot is required. If no <file> item is isKernel="true", no reboot requirement
         detection will be done.
         Only *the last* <file> with isKernel="true" listed is used as the kernel identifier. -->
    <fileChecks>
        <!-- RELATIVE paths to /boot -->
        <file>initramfs-linux.img</file>
        <file>intel-ucode.img</file>
        <file>memtest86+/memtest.bin</file>
        <file isKernel="true">vmlinuz-linux</file>
    </fileChecks>
    <!-- These are system paths to sync to the ESPs. They are synced recursively.
            "source" should be absolute.
            "target" should be relative (to the ESP mount).
            "pattern" is a regex to match to restrict *filenames* to sync. Use ".*" for all files. -->
    <syncPaths>
        <!-- For example, these are grub theme files. -->
        <path source="/usr/share/grub/themes" target="grub/themes" pattern=".*"/>
        <!-- These are grub modules - specifically, UEFI. -->
        <path source="/usr/lib/grub/x86_64-efi" target="grub/x86_64-efi" pattern="^.*\.(mod|lst|sh)$"/>
        <!-- And these are ISO files, in case you're like me and do loop mounting in Grub for rescue situations.
             (e.g. https://wiki.archlinux.org/index.php/Multiboot_USB_drive#Using_GRUB_and_loopback_devices) -->
        <path source="/boot/iso" target="iso" pattern="^.*\.(iso|img)$"/>
    </syncPaths>
</bootsync>
